source 'http://rubygems.org'

gem 'hashie'
gem 'haml'
gem 'json'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib', :require => 'sinatra/reloader'
gem 'haml'
gem 'rack'
gem 'rack-mount', :require => 'rack/mount'
gem 'sinatra-flash', :require => 'sinatra/flash'
gem 'sinatra-redirect-with-flash', :require => 'sinatra/redirect_with_flash'
